# Generated by Django 3.2.5 on 2021-07-08 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('categoria', models.CharField(max_length=50, null=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('titulo', models.CharField(max_length=35, null=True, primary_key=True, serialize=False)),
                ('historia', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=25)),
                ('fecha', models.CharField(max_length=8)),
                ('ubicacion', models.CharField(max_length=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
