# Generated by Django 3.2.5 on 2021-07-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='infocompra',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='producto',
        ),
        migrations.RenameModel(
            old_name='categoria',
            new_name='producto',
        ),
        migrations.DeleteModel(
            name='noticia',
        ),
        migrations.AddField(
            model_name='infocompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
    ]
