/*CREACIÓN USUARIO BASE DE DATOS*/
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER examen IDENTIFIED BY examen;
GRANT CONNECT, RESOURCE TO examen;
ALTER USER examen DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;




INSERT INTO CORE_PRODUCTO VALUES ('1: Bandana Gatitos "13.990"');
INSERT INTO CORE_PRODUCTO VALUES ('2: Bandana Corazones "14.990"');
INSERT INTO CORE_PRODUCTO VALUES ('3: Bandana Anclas "14.990"');
INSERT INTO CORE_PRODUCTO VALUES ('4: Bandana Dulces "12.990"');
INSERT INTO CORE_PRODUCTO VALUES ('5: Bandana Puntos "9.990"');
INSERT INTO CORE_PRODUCTO VALUES ('6: Bandana Hexagonos "14.990"');
INSERT INTO CORE_PRODUCTO VALUES ('7: Placa Plateada "4.990"');
INSERT INTO CORE_PRODUCTO VALUES ('8: Placa Hueso "13.990"');
INSERT INTO CORE_PRODUCTO VALUES ('9: Placa con NFC "13.990"');
INSERT INTO CORE_PRODUCTO VALUES ('10: Correa Plumas "7.990"');
INSERT INTO CORE_PRODUCTO VALUES ('11: Correa Cinturón "7.990"');
INSERT INTO CORE_PRODUCTO VALUES ('12: Correa Elástica "7.990"');
INSERT INTO CORE_PRODUCTO VALUES ('13: Correa Soga "7.990"');
INSERT INTO CORE_PRODUCTO VALUES ('14: Arnés Grande (Perro) "9.990"');
INSERT INTO CORE_PRODUCTO VALUES ('15: Arnés Compacto "5.990"');





